name: Build

on:
  push:
    branches:
    - main
    paths:
    - src/**
  pull_request:
    branches:
    - main
    paths:
    - src/**

env:
  PROJECTS_BUILD: './src/Milochau.Emails.sln'
  PROJECTS_TESTS: './src/Milochau.Emails.sln'
  DOTNET_VERSION: 6.0.x
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and test projects
        uses: amilochau/github-actions/build/netcore@v2
        with:
          dotnetVersion: ${{ env.DOTNET_VERSION }}
          projectsToBuild: ${{ env.PROJECTS_BUILD }}
          projectsToTest: ${{ env.PROJECTS_TESTS }}
