name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  PROJECTS_BUILD: './src/Milochau.Emails.sln'
  PROJECTS_TESTS: './src/Milochau.Emails.sln'
  DOTNET_VERSION: 3.1.x
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Build and test projects
        uses: amilochau/github-actions/build/netcore@v1
        with:
          projectsToBuild: ${{ env.PROJECTS_BUILD }}
          projectsToTest: ${{ env.PROJECTS_TESTS }}
