name: Deploy application (DEV)

on:
  workflow_dispatch:

concurrency: deploy_app_dev

env:
  PROJECTS_BUILD: './src/Milochau.Emails.App.sln'
  PROJECTS_PUBLISH: './src/Milochau.Emails'
  INFRA_DEPLOY_TEMPLATE_PATH: './templates/functions/template.bicep'
  INFRA_DEPLOY_PARAMETERS_PATH: './application/.github/infrastructure/deploy-app.dev.json'
  INFRA_REGISTER_TEMPLATE_PATH: './templates/functions/api-registration.bicep'
  INFRA_REGISTER_PARAMETERS_PATH: './application/.github/infrastructure/register-app.dev.json'
  INFRA_RG_NAME: 'mil-emails-dev-rg'
  INFRA_RG_LOCATION: 'westeurope'
  INFRA_APP_NAME: 'mil-emails-dev-fn'
  INFRA_HEALTH: 'https://mil-emails-dev-fn.azurewebsites.net/api/health/light'
  DOTNET_VERSION: 5.0.x
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  TEMPLATES_VERSION: v6

jobs:
  deploy_infra:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v2 # For parameters file
        with:
          path: application
      - name: Deploy infrastructure
        uses: amilochau/github-actions/deploy/infrastructure@v1
        with:
          azureTemplateVersion: ${{ env.TEMPLATES_VERSION }}
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
          resourceGroupName: ${{ env.INFRA_RG_NAME }}
          resourceGroupLocation: ${{ env.INFRA_RG_LOCATION }}
          templateFilePath: ${{ env.INFRA_DEPLOY_TEMPLATE_PATH }}
          parametersFilePath: ${{ env.INFRA_DEPLOY_PARAMETERS_PATH }}

  deploy_app:
    name: Deploy application
    needs: deploy_infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x' # See https://github.com/Azure/azure-functions-dotnet-worker/wiki/Known-issues#net-core-31-dependency
      - name: Deploy Azure Functions application
        uses: amilochau/github-actions/deploy/functions@v1
        with:
          projectsToBuild: ${{ env.PROJECTS_BUILD }}
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
          applicationName: ${{ env.INFRA_APP_NAME }}
          projectsToPublishPath: ${{ env.PROJECTS_PUBLISH }}
          healthUrl: ${{ env.INFRA_HEALTH }}
