name: Deploy libraries

on:
  workflow_dispatch:

concurrency: deploy_libraries

env:
  PROJECTS_BUILD: './src/Milochau.Emails.Sdk.sln'
  PROJECTS_LIBRARIES: './src/Milochau.Emails.Sdk.sln'
  VERSION_FILE: './src/Directory.Build.props'
  NUGET_URL: 'https://nuget.pkg.github.com/amilochau/index.json'
  DOTNET_VERSION: 6.0.x
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  deploy:
    name: Deploy libraries
    runs-on: ubuntu-latest
    environment: PKG
    steps:
      - uses: actions/checkout@v3
      - name: Deploy libraries
        uses: amilochau/github-actions/release/nuget@v3
        with:
          dotnetVersion: ${{ env.DOTNET_VERSION }}
          projectsToBuild: ${{ env.PROJECTS_BUILD }}
          projectsToPublish: ${{ env.PROJECTS_LIBRARIES }}
          versionFile: ${{ env.VERSION_FILE }}
          githubPackagesUrl: ${{ env.NUGET_URL }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          nugetOrgToken: ${{ secrets.NUGETORG_TOKEN }}
