name: Deploy dependencies (LOCAL)

on:
  workflow_dispatch:

concurrency: deploy_deps_loc

env:
  INFRA_TYPE: 'functions/local-dependencies'
  INFRA_PARAMETERS_PATH: './application/.github/infrastructure/deploy-app.local.json'
  INFRA_RG_NAME: 'mil-emails-local-rg'
  INFRA_RG_LOCATION: 'westeurope'
  TEMPLATES_VERSION: v7

jobs:
  deploy_infra:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    environment: LOCAL
    steps:
      - uses: actions/checkout@v2 # For parameters file
        with:
          path: application
      - name: Deploy infrastructure
        uses: amilochau/github-actions/deploy/infrastructure@v2
        with:
          azureTemplateVersion: ${{ env.TEMPLATES_VERSION }}
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
          resourceGroupName: ${{ env.INFRA_RG_NAME }}
          scopeLocation: ${{ env.INFRA_RG_LOCATION }}
          templateType: ${{ env.INFRA_TYPE }}
          parametersFilePath: ${{ env.INFRA_PARAMETERS_PATH }}
