name: Deploy application (DEV)

on:
  workflow_dispatch:

concurrency: deploy_app_dev

env:
  PROJECTS_PUBLISH: './src/Milochau.Emails'
  INFRA_DEPLOY_TEMPLATE_PATH: './templates/functions/template.bicep'
  INFRA_DEPLOY_PARAMETERS_PATH: './application/.github/infrastructure/deploy-app.dev.json'
  INFRA_REGISTER_TEMPLATE_PATH: './templates/functions/api-registration.bicep'
  INFRA_REGISTER_PARAMETERS_PATH: './application/.github/infrastructure/register-app.dev.json'
  INFRA_RG_NAME: 'mil-emails-dev-rg'
  INFRA_RG_LOCATION: 'westeurope'
  INFRA_APP_NAME: 'mil-emails-dev-fn'
  DOTNET_VERSION: 6.0.x
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  TEMPLATES_VERSION: v7

jobs:
  deploy_infra:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v3 # For parameters file
        with:
          path: application
      - name: Deploy infrastructure
        uses: amilochau/github-actions/deploy/infrastructure@v2
        with:
          azureTemplateVersion: ${{ env.TEMPLATES_VERSION }}
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
          resourceGroupName: ${{ env.INFRA_RG_NAME }}
          scopeLocation: ${{ env.INFRA_RG_LOCATION }}
          templateType: ${{ env.INFRA_DEPLOY_TYPE }}
          parametersFilePath: ${{ env.INFRA_DEPLOY_PARAMETERS_PATH }}

  deploy_app:
    name: Deploy application
    needs: deploy_infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Azure Functions application
        uses: amilochau/github-actions/deploy/functions@v2
        with:
          dotnetVersion: ${{ env.DOTNET_VERSION }}
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
          applicationName: ${{ env.INFRA_APP_NAME }}
          projectsToPublishPath: ${{ env.PROJECTS_PUBLISH }}
