name: Deploy application (PRD)

on:
  workflow_dispatch:
    inputs:
      forceDeployment:
        description: Force infrastructure deployment if the last infrastructure template used is the same as the current one
        required: false
        default: false
        type: boolean

concurrency: deploy_app_prd

env:
  PROJECTS_PUBLISH: './src/Milochau.Emails'
  INFRA_DEPLOY_TYPE: 'functions'
  INFRA_DEPLOY_PARAMETERS_PATH: './application/.github/infrastructure/deploy-app.prd.json'
  INFRA_REGISTER_TYPE: 'functions/api-registration'
  INFRA_REGISTER_PARAMETERS_PATH: './application/.github/infrastructure/register-prd.dev.json'
  INFRA_RG_NAME: 'mil-emails-prd-rg'
  INFRA_RG_LOCATION: 'westeurope'
  INFRA_APP_NAME: 'mil-emails-prd-fn'
  DOTNET_VERSION: 6.0.x
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  TEMPLATES_VERSION: v8

jobs:
  deploy_infra:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    environment: PRD
    steps:
      - uses: actions/checkout@v3 # For parameters file
        with:
          path: application
      - name: Deploy infrastructure
        uses: amilochau/github-actions/deploy/infrastructure@v3
        with:
          azureTemplateVersion: ${{ env.TEMPLATES_VERSION }}
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
          resourceGroupName: ${{ env.INFRA_RG_NAME }}
          scopeLocation: ${{ env.INFRA_RG_LOCATION }}
          templateType: ${{ env.INFRA_DEPLOY_TYPE }}
          parametersFilePath: ${{ env.INFRA_DEPLOY_PARAMETERS_PATH }}
          forceDeployment: ${{ github.event.inputs.forceDeployment }}

  deploy_app:
    name: Deploy application
    needs: deploy_infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Azure Functions application
        uses: amilochau/github-actions/deploy/functions@v3
        with:
          dotnetVersion: ${{ env.DOTNET_VERSION }}
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
          resourceGroupName : ${{ env.INFRA_RG_NAME }}
          applicationName: ${{ env.INFRA_APP_NAME }}
          projectsToPublishPath: ${{ env.PROJECTS_PUBLISH }}
